ARG BASE_IMAGE=crpi-vrt7o5qsysdzjsbh.cn-shanghai.personal.cr.aliyuncs.com/zycube/demo:base-latest

#########################################################################################################
#### 构建镜像
#########################################################################################################
FROM ${BASE_IMAGE}

ARG COMPOSER_VERSION="2.9.5"

RUN set -eux; \
    # \
    # Disable Zend OpCache
    rm -rf /tmp/opcache; mkdir -p /tmp/opcache; chmod -R 0777 /tmp/opcache; \
    rm -rf /usr/local/etc/php/conf.d/*opcache.ini; touch /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini; \
    { \
        php -r "echo version_compare(PHP_VERSION, '8.5.0', '<') ? 'zend_extension=opcache' . PHP_EOL : '; PHP 8.5+ 默认内置 opcache,无需 zend_extension=opcache' . PHP_EOL;"; \
        echo "opcache.enable=0"; \
        echo "opcache.enable_cli=0"; \
    } > /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini; \
    # \
    # Update
    apk update; \
    #
    # Install build dependencies
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS; docker-php-source extract; \
    #
    # Install git
    apk add --no-cache git; \
    #
    # Install subversion
    apk add --no-cache subversion; \
    #
    # Install Zip ext
    apk add --no-cache libzip-dev; \
    apk add --no-cache --virtual .build-deps-ext-zip zlib-dev; \
    #docker-php-ext-install zip; \
    apk del --no-network .build-deps-ext-zip; \
    #
    # Install Composer
    if [ -n "$COMPOSER_VERSION" ]; then \
        curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer --version="$COMPOSER_VERSION"; \
    else \
        curl -sfL https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer; \
    fi; \
    chmod +x /usr/bin/composer; \
    #
    # Clear \
    docker-php-source delete; pecl clear-cache || true; apk del --no-network .build-deps; \
    rm -rf "/tmp/opcache/*" "${LOG_PATH}/*"

CMD /usr/bin/composer
